### ISSUE TITLE
Review all primary keys

### ISSUE THREAD

**Issue by aabounegm** [illright/innopoints-backend#15]
Most tables have the primary key simply an auto-incremented integer id. Some of them, though, would make more sense to have a different meaningful primary key, such as tables whose [weak] entities are associated with exactly one entity of another table. For example, VolunteeringReport can have its primary key be the application_id

**Comment by illright** [comment]
# Activity

Already keyed by (`id`)
**Pros**: short and efficient
**Cons**: redundant data uniqueness, overly large IDs in URLs

Could be keyed by (`project_id`, `name`)
**Pros**: the uniqueness of activities within a project
**Cons**: the name does not necessarily stay constant, wherever the activity is linked, all the fields must be copied

Could be keyed by (`id`, `project_id`)
**Pros**: the IDs in URLs don't get too large and stay independent from project to project
**Cons**: autoincrementing involves storing the last activity ID for each project, rather than one last ID per database, wherever the activity is linked, all the fields must be copied

# Account

Already keyed by (`email`)
**Pros**: will not change, every member of the university has one
**Cons**: a long string is not the best candidate for a primary key

Could be keyed by (`id`)
**Pros**: short and efficient
**Cons**: redundant data uniqueness

# Volunteering Application

Already keyed by (`id`)
The usual pros and cons of ID primary keys

Could be keyed by (`applicant`, `activity`)
**Cons**: the key is large (if the activity key becomes multipart), not as efficient

# Variety

Similar to Activity with respect to Product instead of Project

# Volunteering Report

Could be keyed by (`application`, `reporter`)
**Pros**: no redundant uniqueness
**Cons**: if the application key is chosen to be large, this key will be just as large

# Feedback

Could be keyed by (`application`)
**Pros**: no redundant uniqueness
**Cons**: if the application key is chosen to be large, this key will be just as large
