### ISSUE TITLE
The DELETE endpoint for static files is a vulnerability

### ISSUE THREAD

**Issue by illright** [illright/innopoints-backend#43]
A logged in user can arbitrarily delete files on the server, messing up the existing objects.

There are two solutions:
- prohibit deletion of static files
- store the owner of each file and allow only the owner to delete the file

The first option looks more attractive to me.

**Comment by aabounegm** [comment]
I vote for storing the owner and only allowing admins to delete anything
It is kind of important to be able to know who uploaded something.

**Comment by illright** [comment]
But do we really need deletion? The only use case I see is when the frontend mistakenly uploads a wrong picture and requests its deletion right away. Or when a project is deleted, which rarely happens.

**Comment by illright** [comment]
As for who uploaded something, I'm not sure it's that important. If it is to make an appearance on the website, it's either a project or a project (products are only created by the admin), so we know who uploaded what. As for files that just sit in the storage, we don't really care and we will probably never inspect that.

**Comment by aabounegm** [comment]
One case is if a product is no longer produced and will be deleted, we don't its images just lurking around. I get that it will not happen often, but in case any errors happen, we don't want to have to access the file system in order to remove some file. At least allow admins only to ever delete them.
That reminds me, shouldn't we set a maximum size for a file/image?

**Comment by illright** [comment]
Yes, we definitely should, but we might also look into server-side compression options. And not make the limit too restrictive, like 15 MB
